### ISSUE TITLE
Reden TODO list

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#83]
**If you would like to participate in our project, please open another issue to discuss with us instead of commenting on this issue directly.**

- Coding - Development on Reden Mod itself.
  - Undo (finished)
  - Reden Version Control (RVC) - Please be sure that you have enough understanding about Git (https://zhuanlan.zhihu.com/p/45510461)
    - [ ] documents on [wiki](wiki.redenmc.com)
    - [ ] RVC selections
      - [ ] Auto detecting (partially done, see trackpoints, we still need to improve its performance, refactor may be taken)
      - [ ] Cuboid #101
      - [ ] Whole map
      - [ ] Litematica #101
    - [ ] Remote git repositories
      - [ ] Gitee integration
      - [ ] Github integration
    - [ ] RVC main GUIs (High priority)
    - [ ] Huge buildings
      - That building is too huge for us so it exceeds the view distance, we have to ask the player to move around or send a request to the server to get all the data.
  - Reden Debugger - We don't have any developing plan recently, contact me if you are interested.
    - [ ] Like a debugger in your IDE, it provides features such as pausing the game, tick stage trace (like stack trace), step into, step over, reset, and replay!
    - [ ] Participate in our discussions! #66 #67
  - Misc
    - [ ] Client Notifications #74
    - [ ] Superright Target Block Renderer #73 #93
      - Related feature: wormhole
      
- Community
  - [ ] Code of Conduct #89 
  - [ ] Contribution Guide (code) #89
  - [ ] Terms of Service
  - [ ] Wiki rules and contribution guides
  - [ ] Discord
    - [ ] "Share to discord" bot
      This bot can send a card to a specified channel, including link to download and basic info, requiring server owner to invite the bot.
  - [ ] QQ Group
  - [ ] Moderators
    - We need more people who are experienced on open-source projects or MC / TMC and who can help with community stuff.

- Web
  - [ ] Reden api (integrated with Reden Mod, providing online Minecraft account verifying, usage telemetry, account system, etc)
    - kotlin / ktor
  - [ ] Reden official website
    - Tech stack: vue & vuetify
    - admin pages
    - improve account system
    - activity page
    - notifications (including mod updates, rvchub starts, forks, issues, PRs)

**Comment by zly2006** [comment]
~~Update this issue~~
